### ISSUE TITLE
Midi player not working

### ISSUE THREAD

**Issue by juancopi81** [cifkao/html-midi-player#5]
I am using the midi player in a personal project, it was working fine until yesterday, but today the play button is disabled:

![image](https://user-images.githubusercontent.com/4313860/99884759-9ebff580-2bfe-11eb-8c53-bafa2f8006f8.png)

When I see the console it shows me the following error: Uncaught (in promise) TypeError: h.ToneAudioBuffers is not a constructor:

![image](https://user-images.githubusercontent.com/4313860/99884807-dcbd1980-2bfe-11eb-9dc9-0ca033cba26c.png)

My project is at https://www.komposair.com/ I am not sure if it is an error on my end or if this is the place to report it... but since it was working fine I thought it is something else. Any help would be appreciated...

**Comment by cifkao** [comment]
Thanks for reporting this! It turns out `@magenta/music` got upgraded today to version 1.21.0 and now depends on a more recent major version of `tone` (14.7.58). Upgrading `tone` to this version seems to fix the problem. It may be a good idea to pin exact versions of  the libraries to ensure that upgrades like this don't break your project. I think I will do the same in my examples. E.g.:

```html
<script src="https://cdn.jsdelivr.net/combine/npm/tone@14.7.58,npm/@magenta/music@1.21.0/es6/core.js,npm/focus-visible@5,npm/html-midi-player@1.1.0"></script>
```

**Comment by juancopi81** [comment]
Great! Thank you very much
