### ISSUE TITLE
Changing programmatically src does not load the midi file

### ISSUE THREAD

**Issue by francoisschwarzentruber** [cifkao/html-midi-player#57]
Very nice player! However when I do:
           midiPlayer.src = "https://magenta.github.io/magenta-js/music/demos/melody.mid";
it does not change the file of the player :(.
Should I run a function to load the file?

**Comment by francoisschwarzentruber** [comment]
The problem was very weird: using a midi-player DOM element is not like a div, span etc. With "midiPlayer" I do not get the DOM element, but a weird object. It works with document.getElementById("midiPlayer"):

document.getElementById("midiPlayer").src = "https://magenta.github.io/magenta-js/music/demos/melody.mid";

Maybe explain that point in the documentation (README.md)?

**Comment by cifkao** [comment]
I guess the "weird object" that you get with `midiPlayer` is (coincidentally) the JavaScript module itself.

AFAIK directly accessing elements by using their ID as a JavaScript identifier is not [generally discouraged](https://stackoverflow.com/a/25325330) exactly because of collisions like this. So I'm not sure this merits a special mention in the documentation.
